### ISSUE TITLE
ARG-MINER website

### ISSUE THREAD

**Issue by esraagithub** [argrecsys/arg-miner#81]
Hello
i can't access ARG-MINER web site (https://bench.cs.vt.edu/argminer) as before. 
was ARG-MINNER removed or transferred to another link

**Comment by ansegura7** [comment]
Hello. Thanks for your interest in this work. We have not changed the name of the repo or the links to it. The public link of the project is https://argrecsys.github.io/arg-miner/ and the link of the repo is https://github.com/argrecsys/arg-miner
Kind regards

**Comment by ansegura7** [comment]
I will close this issue.
